apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-ms-deployment
  labels:
    app: hello-ms-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-ms
  template:
    metadata:
      labels:
        app: hello-ms
    spec:
      containers:
      - name: hello-ms
        image: facundor/hello-ms:1.0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: DB_CONNECTION
          value: "mongodb://mongo-service:27017"