apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo-ctrl
  name: mongo-replication-ctrl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo-controller
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017